---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "LesGV.com"
subtitle: "Tableau de bord"
logo: "assets/images/logosquare2.svg"
#icon: "fas fa-chess-board" # Optional icon

header: true
#footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.
footer: 'LesGV.com gère la partie informatique des <a href="https://www.lesgrandsvoisins.com">GrandsVoisins.com</a> et de <a href="https://www.agoodvilalge.com">AGoodVillage.com</a>.'
columns: "auto"
defaults:
  layout: "list"
  colorTheme: "light"
stylesheet:
  - "assets/custom.css"
# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

## Optional message
#message:
#  #url: https://b4bz.io
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Démarrage !"
#  icon: "fa fa-grin"
#  content: "Ceci est une première version du tableau de bord <a href='https://www.lesgv.com'>lesgv.com</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Le Digital des Grands Voisins"
    icon: "fa-solid fa-terminal"
    url: "https://wiki.lesgrandsvoisins.com/fr/activites/digital"
    target: "_blank" # optional html a tag target attribute
  - name: "Les Activités des Grands Voisins"
    icon: "fa-solid fa-icons"
    url: "https://com.lesgrandsvoisins.com/c/activites/21"
    target: "_blank" # optional html a tag target attribute
  # this will link to a second home page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  - name: "Mailing List"
    icon: "fa-solid fa-newspaper"
    url: "https://www.lesgrandsvoisins.com/fr/#rencontre" 
    target: "_blank" # optional html a tag target attribute
  - name: "English"
    icon: "fa-solid fa-language" 
    url: "/en/"
# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Sites"
    icon: "fas fa-globe"
    items:
      - name: "WWW."
        logo: "assets/fasvg/globe-solid.svg"
        subtitle: "Site Web Public"
        tag: "website"
        keywords: "Les Grands Voisins, Website, Public, Présentation"
        url: "https://www.lesgrandsvoisins.com/fr/"
        target: "_blank" # optional html a tag target attribute
      - name: "Wiki."
        logo: "assets/fasvg/book-open-reader-solid.svg"
        subtitle: "Wiki documentaire"
        tag: "wiki"
        keywords: "Les Grands Voisins, Références, Aide, Infomations, Documentation, Wiki, Edition collective"
        url: "https://wiki.lesgv.com/fr/home"
        target: "_blank" # optional html a tag target attribute
      - name: "Com. (Forum.)"
        logo: "assets/fasvg/comment-solid.svg"
        subtitle: "Forum de communication"
        tag: "forum"
        keywords: "Forum, Discourse, Communautaire, Comptes, Discussion"
        url: "https://com.lesgrandsvoisins.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "Blog."
        logo: "assets/fasvg/rss-solid.svg"
        subtitle: "Blog des nouvelles des GrandsVoisins.com"
        tag: "communication"
        keywords: "Ghost, Blog, News, Communication, Infos"
        url: "https://blog.lesgrandsvoisins.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "Forge."
        logo: "assets/fasvg/pen-ruler-solid.svg"
        subtitle: "Entrepôt de codes sources et de gestion de projets"
        tag: "forge"
        keywords: "Gitea, Forge, Git, Tickets, Issues, Billets, Projets, Gestion de projet, Code source"
        url: "https://forge.lesgv.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "AppGV.com/en"
        logo: "assets/fasvg/language-solid.svg"
        subtitle: "This Dashboard in English"
        tag: "English"
        keywords: "Dashboard English"
        url: "/en/"
      - name: "LesGV.com"
        logo: "assets/fasvg/gears-solid.svg"
        subtitle: "Ce tableau de bord fait autrement"
        tag: "Tableau de bord"
        keywords: "Tableau de bord, LesGV"
        url: "https://www.lesgv.com/fr"
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Visio. (Meet.)"
        logo: "assets/fasvg/video-solid.svg"
        subtitle: "Visioconférence"
        tag: "app"
        keywords: "Visioconférence, Réunions, Visio, Meet, Jitsi"
        url: "https://visio.lesgv.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "Mail./SOGo"
        logo: "assets/fasvg/envelope-open-text-solid.svg"
        subtitle: "SOGo Webmail avec Contacts et Agenda"
        tag: "webmail"
        keywords: "Webmail, Contacts, Email, Calendrier, Agenda, Carnet d'addresses"
        url: "https://mail.lesgv.com/SOGo/so/login?language=French"
        target: "_blank" # optional html a tag target attribute
      - name: "Drive."
        logo: "assets/fasvg/cloud-solid.svg"
        subtitle: "Drive dans le cloud avec documents synchronisés, partagables et éditables"
        tag: "cloud"
        keywords: "Drive, Docs, Markdown, Cloud, Seafile, Synchro, Partage"
        url: "https://drive.lesgv.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "ID."
        logo: "assets/fasvg/street-view-solid.svg"
        subtitle: "Papiers d'identitié des GrandsVoisins.com"
        tag: "compte"
        keywords: "KeyCloak, Mot de passe, Identité, Compte, Single Sign-on, SSO, Authentification"
        url: "https://id.lesgv.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pass."
        logo: "assets/fasvg/star-of-life-solid.svg"
        subtitle: "Gestion de ses mots de passe"
        tag: "app"
        keywords: "KeePass, KeeWeb, Gestion de mots de passe"
        url: "https://pass.lesgv.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "Cal."
        logo: "assets/fasvg/address-book-solid.svg"
        subtitle: "Caldav carnets d'addresses et agendas"
        tag: "app"
        keywords: "Radicale, CalDav, Agenda, Carnets d'addresses"
        url: "https://cal.lesgrandsvoisins.com/radicale/.web/"
        target: "_blank" # optional html a tag target attribute
      - name: "Fossil."
        logo: "assets/fasvg/pen-ruler-solid.svg"
        subtitle: "Fossil gestionnaire de codes sources et de projets"
        tag: "forge"
        keywords: "DevOps, Fossil-SCM, Source-Code Management, Gestion de projet, Gestion de codes sources"
        url: "https://fossil.lesgrandsvoisins.com/"
        target: "_blank" # optional html a tag target attribute
  - name: "Gestion de contenus"
    icon: "fas fa-pen"
    items:
      - name: "Web./Login"
        logo: "assets/fasvg/pen-solid.svg"
        subtitle: "Edition de contenus webs"
        tag: "webmaster"
        keywords: "ApostropheCMS, Système de gestion de contenu, Edition de sites web, Editorial, Communication, Edition, Compser des sites webs"
        url: "https://web.lesgv.com/Login"
        target: "_blank" # optional html a tag target attribute
      - name: "Blog./ghost"
        logo: "assets/fasvg/rss-solid.svg"
        subtitle: "Edition du blog / serveur de news"
        tag: "journaliste"
        keywords: "Ghost, Editorial, Edition, Author, Blog, News, Boackoffice, Articles"
        url: "https://blog.lesgrandsvoisins.com/ghost"
        target: "_blank" # optional html a tag target attribute
      - name: "LesGV.com/Login"
        logo: "assets/fasvg/pen-solid.svg"
        subtitle: "Edition du contenu du site LesGV.com"
        tag: "webmaster"
        keywords: "Edition du site lesgv.com"
        url: "https://www.lesgv.com/Login"
        target: "_blank" # optional html a tag target attribute
      - name: "List."
        logo: "assets/fasvg/envelopes-bulk-solid.svg"
        subtitle: "Emailing: Listes de publemailing"
        tag: "emailing"
        keywords: "ListMonk, Emailing, Listes de diffusion"
        url: "https://list.lesgrandsvoisins.com/"
        target: "_blank" # optional html a tag target attribute
  - name: "Administration"
    icon: "fas fa-gears"
    items:
      - name: "Mail./iredadmin"
        logo: "assets/fasvg/envelope-open-text-solid.svg"
        subtitle: "Administration du serveur d'email"
        tag: "backoffice"
        keywords: "iRedMail, Backoffice, WebAdmin"
        url: "https://mail.lesgv.com/iredadmin"
        target: "_blank" # optional html a tag target attribute
      - name: "Admin."
        logo: "assets/fasvg/sitemap-solid.svg"
        subtitle: "Gestion LDAP des Comptes (Backoffice)"
        tag: "tools"
        keywords: "Web2Ldap, LDAP, Client LDAP, Backoffice"
        url: "https://admin.village.tel/"
        target: "_blank" # optional html a tag target attribute